services:
  postgres:
    container_name: postgres
    build: ./app
    volumes:
      - ./postgres-database:/var/lib/postgresql/data
      - ./sqlite:/data
      - ./pgbadger/pg_log:/var/lib/postgresql/data/pg_log
      - ./app/config/postgresql.conf:/var/lib/postgresql/data/postgres-database/postgresql.conf:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bd-p2
      POSTGRES_NAME: postgres14
      PGDATA: /var/lib/postgresql/data/postgres-database
      PGPORT: "5432"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "15432:5432"
      - "2345:2345"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    networks:
      postgres-network:
        ipv4_address: 100.100.0.10

  #pgloader:
  #  build: ./pgloader
  #  container_name: pgloader
  #  volumes:
  #    - ./sqlite:/data
  #    - ./postgres-database:/var/lib/postgresql/data
  #  depends_on:
  #    - postgres
  #  entrypoint: ["/usr/local/bin/entrypoint.sh"]
  #  mem_limit: 8g
  #  mem_reservation: 7g
  #  networks:
  #    - postgres-network

  barman:
    build: ./barman
    container_name: barman
    volumes:
      - ./barman/backup:/var/lib/barman
      - ./barman/config/barman.conf:/etc/barman.conf:rw
      - ./barman/config/data:/etc/barman.d:rw
    ports:
      - "222:22"  
    environment:
      - BARMAN_DB_HOST=postgres
      - BARMAN_DB_USER=postgres
      - BARMAN_DB_PASSWORD=postgres
      - PGPASSWORD=postgres 
    depends_on:
      - postgres
    networks:
      postgres-network:
        ipv4_address: 100.100.0.20

  pgbadger:
    container_name: pgbadger
    build: ./pgbadger
    volumes:
      - ./pgbadger/pg_log:/logs
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

  temboard:
    build:
      context: ./temboard
      args:
        TEMBOARD_VERSION: "8.2.1"
    image: temboard:latest
    container_name: temboard
    volumes:
      - ssl:/etc/ssl/certs  
      - pgdata:/var/lib/postgresql/data
      - home:/home/temboard
      - ./temboard/config/temboard.conf:/home/temboard/temboard.conf:rw
    ports:
      - 3010:8888
      - 3110:5431
    depends_on:
      - postgres
    networks:
      postgres-network:
        ipv4_address: 100.100.0.30

volumes:
  ssl:
    name: temboard-ssl
    driver: local
  pgdata:
    name: temboard-pgdata
    driver: local
  home:
    name: temboard-home
    driver: local  
networks: 
  postgres-network:
    name: postgres-network
    driver: bridge
    ipam:
      config:
        - subnet: 100.100.0.0/16
